.\" Manuel pour la bilbiothèque Colors
.TH Colors 7 "20/10/19" "Version 1.0" "Manuel Colors"

.SH NOM
.B Colors
permet d\'afficher du texte en couleur dans le terminal
.SH TYPE
Bibliothèque Bash

.SH DESCRIPTION
Colors vous permet d\'importer les couleurs suivantes : 
.TP
- noir : $black
.TP
- rouge : $black
.TP
- vert : $black
.TP
- jaune : $black
.TP
- bleu : $black
.TP
- rose : $black
.TP
- cyan : $black
.TP
- gris : $black
.TP

.SH OPTIONS
Aucune options
.SH VOIR AUSSI
source
.SH ERREURS \n
Pas de bug connu
.SH AUTHOR \n
Nicolas Le Guerroué - nicolasleguerroue@gmail.com
