.\" Manuel pour la bilbiothèque Network
.TH Network 7 "20/10/19" "Version 1.0" "Manuel Network"

.SH NOM
.B Network
Permet de scanner le réseau et d'attendre une connexion Internet
.SH TYPE
Bibliothèque Bash

.SH DESCRIPTION
Network vous permet de : 
.TP
- scanner le réseau : Scan [Masque de sous-réseau] 
.TP
- Vérifier la présence de réseau : NetworkIsAvailable retorune True si réseau
.TP
- La fonction WaitingNetwork tourne en boucle jusqu'à trouver du réseau
.TP



.SH OPTIONS
Aucune options
.SH VOIR AUSSI
source
.SH ERREURS \n
Pas de bug connu
.SH AUTHOR \n
Nicolas Le Guerroué - nicolasleguerroue@gmail.com
