.\" Manuel pour la bilbiothèque Satellite
.TH Satellite 1 "20/10/19" "Version 1.0" "Manuel Satellite"

.SH NOM
.B Satellite
permet de récuperer l'image satellite de l'Europe.
.SH COMMANDE
GetSatellite [EMPLACEMENT]
.SH DESCRIPTION
Satellite vous permet de récuperer une image satellite de l'Europe au format .png
.TP
Cette bibliothèques utilise une API en ligne
.SH OPTIONS
[EMPLACEMENT] 		L'emplacement de l'image sauvegardée et son nom
.SH VOIR AUSSI
source
.SH ERREURS \n
Pas de bug connu
.SH AUTHOR \n
Nicolas Le Guerroué - nicolasleguerroue@gmail.com

