.\" Manuel pour la bilbiothèque Sound
.TH Sound 7 "20/10/19" "Version 1.0" "Manuel Sound"

.SH NOM
.B Sound
Permet de faire de la synthèse vocale en anglais
.SH TYPE
Bibliothèque Bash

.SH DESCRIPTION
On précise la machine : SetMachine [type] avec [type] = 'Raspberry' ou 'Computer' 
.TP
Pour parler, on utilise : Speech [texte en anglais]

.SH OPTIONS
Aucune options
.SH VOIR AUSSI
source
.SH ERREURS \n
Pas de bug connu
.SH AUTHOR \n
Nicolas Le Guerroué - nicolasleguerroue@gmail.com
