.\" Manuel pour la bilbiothèque Time
.TH Time 1 "20/10/19" "Version 1.0" "Manuel Time"

.SH NOM
.B Time
permet de récuperer l\'heure, les jours, mois et années.
.SH COMMANDE
Time 
.SH DESCRIPTION
Time vous permet de récuperer les élements suivants :
.TP
- le temps  : echo $(getTime) 
.TP
- l\'année : echo $(getYear)
.TP
- le mois : echo $(getMonth)
.TP
- le jour de la semaine : echo $(getDay)
.TP
- l\'heure : echo $(getHour)
.TP
- les minutes : echo $(getMinute)
.TP
- les secondes : echo $(getSeconde)
.SH OPTIONS
ANY OPTIONS
.SH VOIR AUSSI
source
.SH ERREURS \n
Pas de bug connu
.SH AUTHOR \n
Nicolas Le Guerroué - nicolasleguerroue@gmail.com

