#!/bin/bash

#Variables globales
source_directory="Softwares"   		#Emplacement relatif du code source du site
source_files="Softwares-install"
errors_output="fails.log"
standard_output="infos.log"

storage="$HOME/.Softwares-install"						#dossier où seront stockées les données du logiciel

source $storage/Zenity
source $storage/Colors
SetTitle "Gestionnaire réseau"


if [[ $(hostname -I) == "" ]];then

	SetSize 400 100
	Print "<b>Le logiciel a quitté.</b> \n Source erreur : <i>absence de réseau internet</i>"
	exit
fi

SetSize 2000 2000
(sudo apt-get update) | zenity --progress --pulsate --auto-close --title='Gestionnaire réseau' --width=500 --height=100 --text='Mise à jour de la liste des paquets...'


#Variables globales
storage="$HOME/.Softwares-install"		#dossier où seront stockées les données du logiciel
source_directory="$storage/Softwares"   		#Emplacement relatif du code source du site
errors_output="$storage/.fails.log"
standard_output="$storage/.infos.log"

#définit le titre du logiciel
SetTitle "Installation des logiciels" 												2>> $errors_output >> $standard_output 						
SetColumnsCheckBox "" "logiciel" "Catégorie" "Détails" 								2>> $errors_output >> $standard_output 

total=()

i=0
for file in `ls $source_directory`; do      2>> $errors_output >> $standard_output       #parcourt une fois chaque logiciel
    
	name=$file 																		2>> $errors_output >> $standard_output 
	type=$(cat $source_directory/$file/$file.type)									2>> $errors_output >> $standard_output 
	description=$(cat $source_directory/$file/$file.infos)							2>> $errors_output >> $standard_output 

	total[${#total[*]}]=TRUE														2>> $errors_output >> $standard_output 
	total[${#total[*]}]="$name"														2>> $errors_output >> $standard_output 
	total[${#total[*]}]="$type"														2>> $errors_output >> $standard_output 
	total[${#total[*]}]="$description"												2>> $errors_output >> $standard_output 
	let i++																			2>> $errors_output >> $standard_output 

done

SetTextCheckBox \
"Veuillez sélectionner les logiciels à installer - \
Nombre de logiciels présent dans la base de données : $i."							2>> $errors_output >> $standard_output 


softwares_install=$(CheckBox "${total[@]}" )  



if [[ $softwares_install != "" ]]; then


	nombre=$(echo $softwares_install | grep -o '|' | wc -l)    	2>> $errors_output >> $standard_output 
	let nombre++ 												2>> $errors_output >> $standard_output 
	echo "Nombre logiciels : " $nombre 							2>> $errors_output >> $standard_output 

	for (( i = 1; i < $nombre; i++ )); do #récupère les différents champs
		executable_file=$(echo "$softwares_install" | cut -d '|' -f$i)			  	
						
		echo -e ">>> Installation de $executable_file [Logiciel $i/$nombre]"	
		sleep 0.2
		$storage/Softwares/$executable_file/$executable_file.install 2>> $errors_output >> $standard_output 
		echo -e "    Installation de $executable_file [ $green OK $default ]"

	done
	
	SetTitle "Sortie standard"
	SetSize 800 200
	TextInfos "$standard_output"  2>> $errors_output >> $standard_output 
	SetTitle "Sortie erreurs"
	TextInfos "$errors_output"  2>> $errors_output >> $standard_output 
	exit

fi




# #sudo mysql --user=root

# #Dans MySql :
# #DROP USER 'root'@'localhost';
# #CREATE USER 'root'@'localhost' IDENTIFIED BY 'password';
# #GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';


